# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noah/works/EKFNav

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noah/works/EKFNav

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/works/EKFNav/CMakeFiles /home/noah/works/EKFNav/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/works/EKFNav/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named novatel

# Build rule for target.
novatel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 novatel
.PHONY : novatel

# fast build rule for target.
novatel/fast:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/build
.PHONY : novatel/fast

#=============================================================================
# Target rules for targets named EKFNav

# Build rule for target.
EKFNav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EKFNav
.PHONY : EKFNav

# fast build rule for target.
EKFNav/fast:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/build
.PHONY : EKFNav/fast

src/HgDataParser.o: src/HgDataParser.cpp.o

.PHONY : src/HgDataParser.o

# target to build an object file
src/HgDataParser.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.o
.PHONY : src/HgDataParser.cpp.o

src/HgDataParser.i: src/HgDataParser.cpp.i

.PHONY : src/HgDataParser.i

# target to preprocess a source file
src/HgDataParser.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.i
.PHONY : src/HgDataParser.cpp.i

src/HgDataParser.s: src/HgDataParser.cpp.s

.PHONY : src/HgDataParser.s

# target to generate assembly for a file
src/HgDataParser.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.s
.PHONY : src/HgDataParser.cpp.s

src/Serial.o: src/Serial.cpp.o

.PHONY : src/Serial.o

# target to build an object file
src/Serial.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.o
.PHONY : src/Serial.cpp.o

src/Serial.i: src/Serial.cpp.i

.PHONY : src/Serial.i

# target to preprocess a source file
src/Serial.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.i
.PHONY : src/Serial.cpp.i

src/Serial.s: src/Serial.cpp.s

.PHONY : src/Serial.s

# target to generate assembly for a file
src/Serial.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.s
.PHONY : src/Serial.cpp.s

src/gnss.o: src/gnss.cpp.o

.PHONY : src/gnss.o

# target to build an object file
src/gnss.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss.cpp.o
.PHONY : src/gnss.cpp.o

src/gnss.i: src/gnss.cpp.i

.PHONY : src/gnss.i

# target to preprocess a source file
src/gnss.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss.cpp.i
.PHONY : src/gnss.cpp.i

src/gnss.s: src/gnss.cpp.s

.PHONY : src/gnss.s

# target to generate assembly for a file
src/gnss.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss.cpp.s
.PHONY : src/gnss.cpp.s

src/gnss_core.o: src/gnss_core.cpp.o

.PHONY : src/gnss_core.o

# target to build an object file
src/gnss_core.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss_core.cpp.o
.PHONY : src/gnss_core.cpp.o

src/gnss_core.i: src/gnss_core.cpp.i

.PHONY : src/gnss_core.i

# target to preprocess a source file
src/gnss_core.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss_core.cpp.i
.PHONY : src/gnss_core.cpp.i

src/gnss_core.s: src/gnss_core.cpp.s

.PHONY : src/gnss_core.s

# target to generate assembly for a file
src/gnss_core.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/gnss_core.cpp.s
.PHONY : src/gnss_core.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/navutils.o: src/navutils.cpp.o

.PHONY : src/navutils.o

# target to build an object file
src/navutils.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/navutils.cpp.o
.PHONY : src/navutils.cpp.o

src/navutils.i: src/navutils.cpp.i

.PHONY : src/navutils.i

# target to preprocess a source file
src/navutils.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/navutils.cpp.i
.PHONY : src/navutils.cpp.i

src/navutils.s: src/navutils.cpp.s

.PHONY : src/navutils.s

# target to generate assembly for a file
src/navutils.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/navutils.cpp.s
.PHONY : src/navutils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... novatel"
	@echo "... EKFNav"
	@echo "... src/HgDataParser.o"
	@echo "... src/HgDataParser.i"
	@echo "... src/HgDataParser.s"
	@echo "... src/Serial.o"
	@echo "... src/Serial.i"
	@echo "... src/Serial.s"
	@echo "... src/gnss.o"
	@echo "... src/gnss.i"
	@echo "... src/gnss.s"
	@echo "... src/gnss_core.o"
	@echo "... src/gnss_core.i"
	@echo "... src/gnss_core.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/navutils.o"
	@echo "... src/navutils.i"
	@echo "... src/navutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

